export const tourDates = [
  {
    date: "2026-06-23",
    city: "Istanbul",
    venue: "Kucukciftlik Park",
    country: "Turkey",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-06-26",
    city: "Helsinki",
    venue: "Suvilahti - TUSKA",
    country: "Finland",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-06-28",
    city: "Almaty",
    venue: "Spartak Stadium",
    country: "Kazakhstan",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-06-30",
    city: "Athens",
    venue: "Release Athens",
    country: "Greece",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-03",
    city: "Barcelona",
    venue: "Barcelona Rock Fest",
    country: "Spain",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-05",
    city: "Lisbon",
    venue: "Evil Live Festival",
    country: "Portugal",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-18",
    city: "Reno, NV",
    venue: "Grand Sierra Resort & Casino",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-19",
    city: "Corning, CA",
    venue: "Obsidian Spirits Amphitheater",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-20",
    city: "Paso Robles, CA",
    venue: "California Mid-State Fair",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-07-31",
    city: "La Crosse, WI",
    venue: "Oktoberfest Grounds",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-08-01",
    city: "Green Bay, WI",
    venue: "Capital Credit Union Park",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-08-08",
    city: "Sturgis, SD",
    venue: "Sturgis Buffalo Chip",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-08-22",
    city: "Palmer, AK",
    venue: "Alaska State Fair",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-08-29",
    city: "Toronto, ON",
    venue: "Scotiabank Arena",
    country: "Canada",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-08-30",
    city: "Toronto, ON",
    venue: "Scotiabank Arena",
    country: "Canada",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-03",
    city: "Montréal, QC",
    venue: "Parc Jean Drapeau",
    country: "Canada",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-05",
    city: "Harrison, NJ",
    venue: "Sports Illustrated Stadium",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-06",
    city: "Harrison, NJ",
    venue: "Sports Illustrated Stadium",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-09",
    city: "Boston, MA",
    venue: "TD Garden",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-11",
    city: "Bristow, VA",
    venue: "Jiffy Lube Live",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-12",
    city: "Charlotte, NC",
    venue: "PNC Music Pavilion",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-15",
    city: "Hershey, PA",
    venue: "Hersheypark Stadium",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-19",
    city: "Shakopee, MN",
    venue: "Mystic Lake Amphitheater",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-22",
    city: "Tinley Park, IL",
    venue: "Credit Union 1 Amphitheatre",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-25",
    city: "Los Angeles, CA",
    venue: "BMO Stadium",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-27",
    city: "Los Angeles, CA",
    venue: "BMO Stadium",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-09-29",
    city: "San Antonio, TX",
    venue: "Alamodome",
    country: "United States",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-07",
    city: "Auckland",
    venue: "Spark Arena",
    country: "New Zealand",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-08",
    city: "Auckland",
    venue: "Spark Arena",
    country: "New Zealand",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-11",
    city: "Adelaide",
    venue: "Entertainment Centre",
    country: "Australia",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-13",
    city: "Melbourne",
    venue: "AAMI Park",
    country: "Australia",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-15",
    city: "Sydney",
    venue: "Allianz Stadium",
    country: "Australia",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-18",
    city: "Brisbane",
    venue: "Entertainment Centre",
    country: "Australia",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
  {
    date: "2026-11-19",
    city: "Brisbane",
    venue: "Entertainment Centre",
    country: "Australia",
    ticketLink: "https://www.megadeth.com/pages/tour#now",
  },
];
