export const tourDates = [
  {
    date: "2025-10-04",
    city: "Zurich",
    venue: "Hallenstadion",
    country: "Switzerland",
    ticketLink: "https://www.ticketmaster.ch",
  },
  {
    date: "2025-10-06",
    city: "Budapest",
    venue: "Budapest Arena",
    country: "Hungary",
    ticketLink: "https://funcode.hu/en/event/1427-disturbed-the-sickness-25th-anniversary-tour",
  },
  {
    date: "2025-10-07",
    city: "Prague",
    venue: "O2 Arena",
    country: "Czech Republic",
    ticketLink: "https://www.ticketmaster.cz",
  },
  {
    date: "2025-10-10",
    city: "Kraków",
    venue: "TAURON Arena",
    country: "Poland",
    ticketLink: "https://www.ticketmaster.pl",
  },
  {
    date: "2025-10-12",
    city: "Paris",
    venue: "Zenith",
    country: "France",
    ticketLink: "https://www.ticketmaster.fr",
  },
  {
    date: "2025-10-14",
    city: "Amsterdam",
    venue: "Ziggo Dome",
    country: "Netherlands",
    ticketLink: "https://www.ticketmaster.nl",
  },
  {
    date: "2025-10-15",
    city: "Brussels",
    venue: "Forest National",
    country: "Belgium",
    ticketLink: "https://www.ticketmaster.be",
  },
  {
    date: "2025-10-17",
    city: "Munich",
    venue: "Olympiahalle",
    country: "Germany",
    ticketLink: "https://www.ticketmaster.de",
  },
  {
    date: "2025-10-18",
    city: "Berlin",
    venue: "Velodrome",
    country: "Germany",
    ticketLink: "https://www.ticketmaster.de",
  },
  {
    date: "2025-10-20",
    city: "Birmingham",
    venue: "Utilita Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-22",
    city: "Dublin",
    venue: "3Arena",
    country: "Ireland",
    ticketLink: "https://www.ticketmaster.ie",
  },
  {
    date: "2025-10-24",
    city: "Manchester",
    venue: "AO Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-26",
    city: "London",
    venue: "The O2 Arena",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
  {
    date: "2025-10-28",
    city: "Glasgow",
    venue: "OVO Hydro",
    country: "United Kingdom",
    ticketLink: "https://www.ticketmaster.co.uk",
  },
];
